name: Bug Report
description: Report a bug or unexpected behavior in the mobile app
title: "[Bug]: "
labels: [bug, needs-triage]
assignees: []

body:
  - type: markdown
    attributes:
      value: "### 📢 **Before submitting, please check if the issue already exists.**"

  - type: input
    id: app_version
    attributes:
      label: "📌 App Version"
      description: "Which version of the app are you using?"
      placeholder: "e.g., 1.2.3"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: "📱 Platform"
      description: "Which platform are you experiencing the issue on?"
      options:
        - iOS
        - Android
        - Both
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: "🛠 OS Version"
      description: "Which version of iOS or Android are you using?"
      placeholder: "e.g., iOS 17.3, Android 14"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "🐛 Describe the Issue"
      description: "Provide a clear and concise description of the issue."
      placeholder: "When I tap the login button, nothing happens..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "How can we reproduce the issue?"
      placeholder: |
        1. Open the app
        2. Tap on 'Login'
        3. Enter credentials and tap 'Sign In'
        4. Observe the issue
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
      placeholder: "I expected to be logged in and redirected to the home screen."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: "❌ Actual Behavior"
      description: "What actually happened?"
      placeholder: "After tapping login, the button becomes unresponsive."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "📜 Logs & Crash Reports (if applicable)"
      description: "Paste any relevant logs or crash reports."
      placeholder: "Attach log output here"
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: "📎 Additional Context"
      description: "Any additional information, screenshots, or recordings?"
      placeholder: "If applicable, add screenshots here."

  - type: checkboxes
    id: confirmation
    attributes:
      label: "✅ Checklist"
      options:
        - label: "I have searched for existing issues before submitting this."
          required: true
        - label: "I have updated the app to the latest version."
        - label: "I have tried clearing the cache and restarting the app."
