name: Major Bug Report
description: Report a critical bug affecting functionality
title: "[Bug]: "
labels: [bug, urgent]
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: "📌 Title"
      description: "Provide a concise title summarizing the issue."
      placeholder: "E.g., 'Login button unresponsive on Android'"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "⚠ Issue Severity"
      description: "How critical is this issue?"
      options:
        - Urgent
        - High
        - Normal
        - Low
    validations:
      required: true

  - type: input
    id: related_issue
    attributes:
      label: "🔗 Related Issue (if any)"
      description: "Reference any related issues by number."
      placeholder: "E.g., #995"

  - type: textarea
    id: expected_behavior
    attributes:
      label: "✅ Expected Behavior"
      description: "What was the user trying to do?"
      placeholder: "E.g., The login button should navigate to the dashboard."
    validations:
      required: true

  - type: textarea
    id: obstacle
    attributes:
      label: "🚧 Obstacle"
      description: "What prevented the user from achieving their goal?"
      placeholder: "E.g., The login button does not respond."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: "🔄 Steps to Reproduce"
      description: "Describe the steps to trigger the issue."
      placeholder: |
        1. Tap 'Login'
        2. Enter credentials
        3. Tap 'Sign In'
        4. Observe issue
    validations:
      required: true

  - type: input
    id: android_ios_version
    attributes:
      label: "📱 Android/iOS Version"
      description: "Specify the OS version."
      placeholder: "E.g., Android 34, iOS 18"
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: "📌 App Version"
      description: "Specify the app version."
      placeholder: "E.g., 2.28.1"
    validations:
      required: true

  - type: dropdown
    id: build_version
    attributes:
      label: "🛠 App Build Version"
      description: "Select the environment where the issue occurred."
      options:
        - DEV
        - TEST
        - PROD
    validations:
      required: true

  - type: textarea
    id: log_data
    attributes:
      label: "📜 Received Logs"
      description: "Paste any relevant logs from debugging."
      placeholder: "Attach log output here"
      render: shell

  - type: textarea
    id: qr_code
    attributes:
      label: "🔑 QR Code for User Login"
      description: "Attach the QR code for debugging login access."

  - type: input
    id: test_group
    attributes:
      label: "🧪 Reproducing Test Group Name"
      description: "Who identified this bug?"
      placeholder: "E.g., Test Group"
    validations:
      required: true

  - type: input
    id: test_user
    attributes:
      label: "👤 Reproducing User Name"
      description: "Who encountered this issue?"
      placeholder: "E.g., Test Elek"
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "📸 Screenshot (Required)"
      description: "Attach a screenshot showing the bug."
    validations:
      required: true

  - type: textarea
    id: video
    attributes:
      label: "🎥 Video (if possible)"
      description: "Attach a video showing how to reproduce the bug."
