name: Kisebb Hiba / Javaslat
description: Jelents egy kisebb hibát, UI problémát vagy javaslatot
title: "[Fejlesztés]: "
labels: [fejlesztés, megbeszélés]
assignees: []

body:
  - type: input
    id: title
    attributes:
      label: "📌 Cím"
      description: "Adj meg egy tömör címet, amely összefoglalja a problémát vagy javaslatot."
      placeholder: "Pl.: 'A gombok elcsúsztak a kezdőképernyőn'"
    validations:
      required: true

  - type: textarea
    id: observation
    attributes:
      label: "🔍 Megfigyelés"
      description: "Írd le, mit vettél észre."
      placeholder: "Pl.: A szöveges elemek egymásra csúsznak a beállítások oldalon."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: "💡 Javasolt Megoldás"
      description: "Adj meg egy lehetséges javítást vagy fejlesztést."
      placeholder: "Pl.: Adjunk hozzá térközt az elemek között."
    validations:
      required: true

  - type: textarea
    id: additional_questions
    attributes:
      label: "❓ További Kérdések"
      description: "Tegyél fel bármilyen releváns kérdést a csapat számára."
      placeholder: "Pl.: Használjunk új betűtípust a jobb olvashatóság érdekében?"

  - type: dropdown
    id: priority
    attributes:
      label: "📌 Prioritás"
      description: "Mennyire fontos ez a probléma?"
      options:
        - Alacsony
        - Normál
        - Magas
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "📸 Képernyőkép (ha van)"
      description: "Csatolj egy képernyőképet a problémáról."

  - type: textarea
    id: video
    attributes:
      label: "🎥 Videó (ha lehetséges)"
      description: "Csatolj egy videót, amely bemutatja a problémát."
